apiVersion: apps/v1
kind: Deployment
metadata:
  name: psgrs-dpl
  labels:
    name: psgrs-dpl
    app: voting-apps-dpk
spec:
  selector:
    matchLabels:
      name: psgrs-pod
      app: demo-voting-app
  template:
    metadata:
      name: psgrs-pod
      labels:
        name: psgrs-pod
        app: demo-voting-app
    spec:
      containers:
        - name: psgrs
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust    