apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-dpl
  labels:
    name: result-dpl
    app: voting-apps-dpl
spec:
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
    