apiVersion: v1
kind: Pod
metadata:
  name: psgrs-pod
  labels:
    name: psgrs-pod
    tier: back-end
    app: demo-voting-app
spec:
  containers:
    - name: psgrs
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust

#git test
        